/**
 * inject-env.mjs — Build-time env injector for Supabase credentials.
 *
 * Reads SUPABASE_URL and SUPABASE_ANON_KEY from process.env (set via .env.local
 * or Netlify/CI environment variables) and writes public/env.js which sets
 * window.__ENV__ so the frontend can read them without a bundler.
 *
 * Usage:
 *   node scripts/inject-env.mjs
 *
 * public/env.js is gitignored — never commit it.
 * Only the public ANON key is written here (safe by design).
 * The service-role key must NEVER be passed to this script.
 *
 * Falls back gracefully: if no env vars are set, writes an empty __ENV__
 * so the frontend falls back to mock-api.js without errors.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');
const outputPath  = resolve(projectRoot, 'public', 'env.js');

// Read from process.env (populated by .env.local via dotenv, or CI env vars)
// We intentionally do NOT use dotenv here to keep the script zero-dependency.
// In local dev: export SUPABASE_URL=... && export SUPABASE_ANON_KEY=... before running.
// Or source a .env.local manually: `set -a && source .env.local && set +a` (bash)
const SUPABASE_URL      = process.env.SUPABASE_URL      ?? '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY ?? '';

// Security guard: reject service-role key if accidentally passed
if (SUPABASE_ANON_KEY.length > 0 && SUPABASE_ANON_KEY.startsWith('eyJ') && SUPABASE_ANON_KEY.length > 300) {
  // Anon keys are ~200 chars; service-role keys are longer. Rough heuristic.
  // Real guard: service-role JWTs contain "role":"service_role" in the payload.
  const payload = Buffer.from(SUPABASE_ANON_KEY.split('.')[1] ?? '', 'base64').toString('utf8');
  if (payload.includes('"service_role"')) {
    console.error('[inject-env] ERROR: SUPABASE_ANON_KEY appears to be a service-role key!');
    console.error('[inject-env] The service-role key must NEVER be placed in public/env.js.');
    process.exit(1);
  }
}

const isConfigured = SUPABASE_URL.startsWith('https://') && SUPABASE_ANON_KEY.length > 0;

// Ensure public/ directory exists
mkdirSync(resolve(projectRoot, 'public'), { recursive: true });

const content = `// AUTO-GENERATED by scripts/inject-env.mjs — DO NOT EDIT
// Regenerate: npm run dev:env
// This file is gitignored. Contains only the public ANON key (safe).
window.__ENV__ = ${JSON.stringify({
  SUPABASE_URL:      SUPABASE_URL,
  SUPABASE_ANON_KEY: SUPABASE_ANON_KEY,
}, null, 2)};
`;

writeFileSync(outputPath, content, 'utf8');

if (isConfigured) {
  console.log(`[inject-env] Written public/env.js with Supabase credentials.`);
  console.log(`[inject-env] URL: ${SUPABASE_URL}`);
} else {
  console.log(`[inject-env] No Supabase credentials found — written empty public/env.js.`);
  console.log(`[inject-env] Site will run in mock mode (mock-api.js fallback).`);
  console.log(`[inject-env] To enable real backend: set SUPABASE_URL and SUPABASE_ANON_KEY then re-run.`);
}
